service: todos-webapp

plugins: 
  - serverless-finch

provider:
  name: aws
  runtime: nodejs14.x
  
custom:
 
  client:
    bucketName: mytodos.web
    #bucketPolicyFile: policy.json
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
